// Meeting Scheduler — config.js
// Generated by setup.html. Do not edit manually.
// API key and bin ID are obfuscated; password is SHA-256 hashed.

const CONFIG = {
  // Obfuscated JSONBin Master Key (3 parts, base64)
  _kp: [
    'JDJhJDEwJHp0d1B5L3NXWkVSMXY=',
    'SUduYThiVFUuNHBPc09TTng2bUo=',
    'bHRqRXFVdUU5Ry5XVFR1QW15Nnk='
  ],

  // Obfuscated JSONBin Bin ID (3 parts, base64)
  _bp: [
    'NjlkN2E1ZGE=',
    'YWFiYTg4MjE=',
    'OTdkZGVhY2M='
  ],

  // SHA-256 hash of admin password
  adminPasswordHash: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',

  // Secret token for the 1-to-1 booking page
  bookingToken: '5v173n6v3a2c3z5x5a5q502h',

  // Reassemble at runtime (not stored as plaintext)
  get jsonbinApiKey() { return this._kp.map(p => atob(p)).join(''); },
  get jsonbinBinId()  { return this._bp.map(p => atob(p)).join(''); },
};